name: "Release"

on:
  push:
    branches:
      - "main"

env:
  FORCE_COLOR: "3"

concurrency: "${{ github.workflow }}-${{ github.ref }}"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-22.04-arm"
    permissions:
      contents: "write"
      id-token: "write"
      pull-requests: "write"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v5"

      - name: "Setup Nix Environment"
        uses: "./.github/actions/setup-nix"

      - name: "Install Dependencies"
        run: |
          nix develop --command pnpm install --frozen-lockfile

      - name: "Create Release Pull Request or Publish to npm"
        id: "changesets"
        uses: "changesets/action@v1.5.3"
        with:
          version: |
            nix develop #.ci --command pnpm changeset version
          title: "release: publish package to npm"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          NPM_TOKEN: "${{ secrets.NPM_TOKEN }}"

      - name: "Publish Package to npm"
        if: steps.changesets.outputs.hasChangesets == 'false' && contains(github.event.head_commit.message, 'publish package')
        run: |
          nix develop --command pnpm release
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          NPM_TOKEN: "${{ secrets.NPM_TOKEN }}"
